version: '3.2' #docker-compose.yml
services:
  sonarqube:
    build:
      context: sonarcube/
    ports:
      - 9020:9020
      - 9092:9092
    container_name: sonarqube
  jenkins:
    build:
      context: jenkins/
    privileged: true
    user: root
    ports:
      - 8090:8080
      - 50000:50000
    container_name: jenkins
    depends_on:
      - sonarqube